document.addEventListener("DOMContentLoaded", () => {
    const startButton = document.querySelector("#start-button");
    if (startButton) {
        startButton.addEventListener("click", () => {
            window.location.href = "lift";
        });
    }

    const quotes = [
    "Success is the sum of small efforts repeated day in and day out.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Do something today that your future self will thank you for.",
    "Every rep counts.",
    "Your pace is the right pace.",
    "Today is another chance to get better.",
    "Hard work beats talent.",
    "You can do hard things.",
    "Nothing works unless you do.",
    "Keep going. You're getting better.",
    "Stay focused. Stay committed.",
    "You don't need to be extreme. Just consistent.",
    "Do it for the results.",
    "You're not tired. You're uninspired.",
    "Train like you mean it.",
    "You'll thank yourself later.",
    "Don't quit. You're closer than you think.",
    "Stronger every day.",
    "Raise the bar.",
    "Your goals don't care how you feel.",
    "Show up. That's the battle.",
    "Do it for your future self.",
    "The work you put in today builds tomorrow.",
    "Push past your limits.",
    "Better sore than sorry.",
    "Hard today. Strong tomorrow.",
    "Let the progress speak.",
    "Quit wishing. Start doing.",
    "Earn your rest.",
    "Make your why stronger than your excuses.",
    "Success requires effort.",
    "Be relentless.",
    "Champions are made when no one is watching.",
    "No shortcuts. Just hard work.",
    "Your only limit is you.",
    "Results happen over time, not overnight.",
    "Be stronger than your strongest excuse.",
    "Work until your idols become rivals.",
    "You're capable of more than you think.",
    "Progress over perfection.",
    "Sweat is your fat crying.",
    "Nobody cares — work harder.",
    "Wake up. Work out. Look good. Feel good.",
    "Discipline creates freedom.",
    "Small steps every day.",
    "Pain is temporary. Pride is forever.",
    "Don't stop when you're tired. Stop when you're done.",
    "Act like a champion before you become one.",
    "Consistency is harder when no one is clapping — do it anyway.",
    "Strive for progress, not perfection.",
    "You didn't come this far to only come this far.",
    "Strength grows in the moments you think you can't go on.",
    "Be the hardest worker in the room.",
    "Success starts with self-discipline.",
    "Show up even when you don't feel like it.",
    "Sweat now. Shine later.",
    "Be better than yesterday.",
    "Make yourself proud.",
    "Work for it.",
    "Grind now. Greatness later.",
    "Your future self is watching.",
    "Excuses change nothing. Actions change everything.",
    "Motivation gets you started. Discipline keeps you going.",
    "Fall in love with the process.",
    "Be the energy you want to attract.",
    "Nothing worth having comes easy.",
    "Push yourself because no one else is going to do it for you.",
    "Your body can stand almost anything — it's your mind you must convince.",
    "Strong mind. Strong body.",
    "Success is built on repetition.",
    "Be obsessed with improvement.",
    "The difference between try and triumph is a little 'umph'.",
    "Dream big. Work hard. Stay focused.",
    "Stay hungry.",
    "Remember why you started.",
    "If it doesn't challenge you, it won't change you.",
    "Suffer the pain of discipline or the pain of regret.",
    "Fall seven times, stand up eight.",
    "Start where you are. Use what you have. Do what you can.",
    "Great things never come from comfort zones.",
    "Work hard in silence. Let success make the noise.",
    "Make sweat your best accessory.",
    "Find your fire.",
    "One workout at a time.",
    "If you're tired, do it tired.",
    "The harder the battle, the sweeter the victory.",
    "Don't limit your challenges — challenge your limits.",
    "Success doesn't come from what you do occasionally, but what you do consistently.",
    "Strong things take time.",
    "Nobody wins by accident.",
    "Stay patient. Stay dedicated.",
    "Fuel your ambition.",
    "Put in the work.",
    "Keep pushing.",
    "Your grind will pay off.",
    "Show up. Work hard. Repeat.",
    "Never settle.",
    "Forward is forward.",
    "One day or day one — you decide."
];

    const quoteElement = document.querySelector("#quote");
    if (quoteElement) {
        quoteElement.textContent = quotes[Math.floor(Math.random() * quotes.length)];
    }
});
